server:
  port: 8020
spring:
  application:
    name: srock-service
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:192.168.4.44:8848,192.168.4.45:8848,192.168.4.46:8848}  # 注册中心地址
      discovery:
        password: nacos
        username: q8!%U!Tqk&n&2Tw